# Basic

favicon: /favicon.svg
logo: /favicon.svg

navlink:
    internal:
        Blog: /
        Archive: /archives/
    external:
        GitHub: https://github.com/XavierWah/hexo-theme-asclepius
        Rss: /atom.xml

# Copyright
startyear: 2022
